<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>afs_bringup</name>
  <version>0.0.0</version>
  <description>Launch for AFS</description>
  <maintainer email="hiranotaichi8@gmail.com">Taichi Hirano</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>afs_central_control</exec_depend>
  <exec_depend>afs_family</exec_depend>
  <exec_depend>afs_therapist</exec_depend>
  <exec_depend>afs_stt</exec_depend>
  <exec_depend>afs_tts</exec_depend>
  <exec_depend>afs_toio</exec_depend>
  <exec_depend>afs_evaluation</exec_depend>
  <exec_depend>afs_viewer</exec_depend>
  <exec_depend>afs_config</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
