#!/usr/bin/env python3
"""
AFS Viewer node.

Receives the FACES IV plot image generated by the Therapist node and displays
it in real time in a Tkinter window. The GUI drawing itself is handled by
`plot_viewer_gui.PlotViewerGUI` (no rclpy dependency); this file only handles
ROS2 subscribing (the communication layer) and fitting a non-blocking spin
into the Tkinter event loop.
"""

import rclpy
from rclpy.node import Node
from std_msgs.msg import String
import tkinter as tk
import os
import argparse
from ament_index_python.packages import get_package_share_directory

from afs_viewer.plot_viewer_gui import PlotViewerGUI


class AFSViewer(Node):
    """ROS2 node (communication layer) that receives plot-update notifications and applies them to the GUI."""

    def __init__(self, gui):
        super().__init__('afs_viewer')
        self.gui = gui
        self.subscription = self.create_subscription(String, 'afs_faces_plot_updated', self.listener_callback, 10)
        self.get_logger().info('AFS Viewer Node started.')

    def listener_callback(self, msg):
        """Tkinter can't be updated directly from outside the main thread, so pass this to the GUI thread using after()."""
        self.gui.master.after(0, self.gui.update_image, msg.data)


def main():
    rclpy.init()
    HOME = os.path.expanduser("~")
    DB_DIR = os.path.join(HOME, "afs/src/afs_database")
    if not os.path.isdir(DB_DIR):
        try:
            DB_DIR = os.path.join(get_package_share_directory('afs_config'), 'afs_database')
        except Exception:
            pass
    parser = argparse.ArgumentParser()
    parser.add_argument("--geometry", type=str, default="")
    args, _ = parser.parse_known_args()

    default_plot_path = os.path.join(DB_DIR, "evaluation_plot.png")

    root = tk.Tk()
    if args.geometry:
        root.geometry(args.geometry)
    else:
        root.geometry("200x200")
    gui = PlotViewerGUI(root, default_plot_path)
    node = AFSViewer(gui)

    def spin():
        """Interleave rclpy.spin_once into the Tkinter event loop every 100ms so the GUI never blocks."""
        if not rclpy.ok():
            node.get_logger().info("Viewer: rclpy is not ok, stopping spin loop.")
            return
        try:
            # Non-blocking spin
            rclpy.spin_once(node, timeout_sec=0)
        except Exception as e:
            node.get_logger().error(f"Viewer spin error: {e}")
        root.after(100, spin)

    root.after(100, spin)

    try:
        root.mainloop()
    except KeyboardInterrupt:
        pass
    finally:
        # Graceful shutdown
        try:
            node.destroy_node()
            rclpy.shutdown()
        except Exception:
            pass


if __name__ == '__main__':
    main()
