#!/usr/bin/env python3
"""
AFS Viewer Node.

Receives FACES IV plot images generated by the Therapist node and displays them
in real time within a Tkinter window. GUI rendering is handled by
`plot_viewer_gui.PlotViewerGUI` (independent of rclpy); this file only manages
ROS2 subscription (the communication layer) and interleaves non-blocking spins
into Tkinter's event loop.

ROS2 Interface:
  Subscription `afs_faces_plot_updated` (String) — Path to the newly generated
                plot image, or the literal "RESET".
This node does not publish any topics: it is display-only.

Structural problem addressed here: Both Tkinter and rclpy desire to hold the
main execution loop indefinitely. Here, Tkinter owns the main loop, and rclpy is
invoked via periodic, short non-blocking calls (see `spin`).
"""

import rclpy
from rclpy.node import Node
from std_msgs.msg import String
import tkinter as tk
import os
import argparse
from ament_index_python.packages import get_package_share_directory

from afs_viewer.plot_viewer_gui import PlotViewerGUI


class AFSViewer(Node):
    """ROS2 node (communication layer) that receives plot update notifications and reflects them in the GUI."""

    def __init__(self, gui):
        super().__init__('afs_viewer')
        self.gui = gui
        self.subscription = self.create_subscription(String, 'afs_faces_plot_updated', self.listener_callback, 10)
        self.get_logger().info('AFS Viewer Node started.')

    def listener_callback(self, msg):
        """Delegate image updates to the GUI thread via after() since Tkinter cannot be updated directly from external threads.

        `after(0, ...)` tells Tkinter to execute this on the main GUI thread as soon
        as possible. Calling `update_image` directly here may cause Tkinter crashes.
        """
        self.gui.master.after(0, self.gui.update_image, msg.data)


def main():
    """Entry point for `ros2 run afs_viewer afs_viewer`. The main loop is driven by Tkinter."""
    rclpy.init()
    # The plot is written to the DB directory by the therapist node. Prefer the source
    # tree location, falling back to the installed share directory if not found.
    HOME = os.path.expanduser("~")
    DB_DIR = os.path.join(HOME, "afs/src/afs_database")
    if not os.path.isdir(DB_DIR):
        try:
            DB_DIR = os.path.join(get_package_share_directory('afs_config'), 'afs_database')
        except Exception:
            pass
    parser = argparse.ArgumentParser()
    # Geometry passed from the launch file to place this window in the grid layout
    parser.add_argument("--geometry", type=str, default="")
    # Use parse_known_args because ROS2 passes internal arguments (e.g. --ros-args)
    args, _ = parser.parse_known_args()

    default_plot_path = os.path.join(DB_DIR, "evaluation_plot.png")

    root = tk.Tk()
    if args.geometry:
        root.geometry(args.geometry)
    else:
        root.geometry("200x200")
    gui = PlotViewerGUI(root, default_plot_path)
    node = AFSViewer(gui)

    def spin():
        """Periodically interleave rclpy.spin_once into Tkinter's event loop every 100ms to keep the GUI responsive."""
        if not rclpy.ok():
            node.get_logger().info("Viewer: rclpy is not ok, stopping spin loop.")
            return
        try:
            # Non-blocking spin: timeout_sec=0 processes only already-queued messages
            # and returns immediately, preventing GUI freezes.
            rclpy.spin_once(node, timeout_sec=0)
        except Exception as e:
            node.get_logger().error(f"Viewer spin error: {e}")
        # Schedule the next check; this keeps the polling loop alive.
        root.after(100, spin)

    root.after(100, spin)

    try:
        root.mainloop()
    except KeyboardInterrupt:
        pass
    finally:
        # Clean shutdown
        try:
            node.destroy_node()
            rclpy.shutdown()
        except Exception:
            pass


if __name__ == '__main__':
    main()
